
#include <opcode/mos65xx.h>
#include <strings.h>
#include <stdlib.h>
#include <stdio.h>

/*
 *  TODO: allocate some macros as static constants so that
 *        preprocessor suffers less... 
 */

#define MOS65XX_MODEFLAG_IND_IDX                MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IND_IDX)
#define MOS65XX_MODEFLAG_STK_REL                MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_STK_REL)
#define MOS65XX_MODEFLAG_PGE                    MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_PGE)
#define MOS65XX_MODEFLAG_IND_LNG                MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IND_LNG)
#define MOS65XX_MODEFLAG_IMM                    MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IMM)
#define MOS65XX_MODEFLAG_ABS                    MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS)
#define MOS65XX_MODEFLAG_LNG                    MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_LNG)
#define MOS65XX_MODEFLAG_IND_IDY                MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IND_IDY)
#define MOS65XX_MODEFLAG_IND                    MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IND)
#define MOS65XX_MODEFLAG_STK_IND_IDY            MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_STK_IND_IDY)
#define MOS65XX_MODEFLAG_IDX                    MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IDX)
#define MOS65XX_MODEFLAG_IND_LNG_IDY            MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IND_LNG_IDY)
#define MOS65XX_MODEFLAG_ABS_IDY                MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS_IDY)
#define MOS65XX_MODEFLAG_ABS_IDX                MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS_IDX)
#define MOS65XX_MODEFLAG_ABS_LNG_IDX            MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS_LNG_IDX)
#define MOS65XX_MODEFLAG_IDY                    MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IDY)
#define MOS65XX_MODEFLAG_ACC                    MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ACC)
#define MOS65XX_MODEFLAG_BLK                    MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_BLK)
#define MOS65XX_MODEFLAG_IMPLIED                MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IMPLIED)
#define MOS65XX_MODEFLAG_PCREL                  MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_PCREL)
#define MOS65XX_MODEFLAG_INVALID                0

#define MOS65XX_CLASS_ALUMEM \
  (MOS65XX_MODEFLAG_IND_IDX \
  | MOS65XX_MODEFLAG_STK_REL \
  | MOS65XX_MODEFLAG_PGE \
  | MOS65XX_MODEFLAG_IND_LNG \
  | MOS65XX_MODEFLAG_IMM \
  | MOS65XX_MODEFLAG_ABS \
  | MOS65XX_MODEFLAG_LNG \
  | MOS65XX_MODEFLAG_IND_IDY \
  | MOS65XX_MODEFLAG_IND \
  | MOS65XX_MODEFLAG_STK_IND_IDY \
  | MOS65XX_MODEFLAG_IDX \
  | MOS65XX_MODEFLAG_IND_LNG_IDY \
  | MOS65XX_MODEFLAG_ABS_IDY \
  | MOS65XX_MODEFLAG_ABS_IDX \
  | MOS65XX_MODEFLAG_ABS_LNG_IDX)

#define MOS65XX_CLASS_BITOPS \
  (MOS65XX_MODEFLAG_PGE \
  | MOS65XX_MODEFLAG_ACC \
  | MOS65XX_MODEFLAG_ABS \
  | MOS65XX_MODEFLAG_IDX \
  | MOS65XX_MODEFLAG_ABS_IDX)

#define MOS65XX_CLASS_LDX \
  (MOS65XX_MODEFLAG_IMM \
  | MOS65XX_MODEFLAG_PGE \
  | MOS65XX_MODEFLAG_ABS \
  | MOS65XX_MODEFLAG_IDY \
  | MOS65XX_MODEFLAG_ABS_IDY)

#define MOS65XX_CLASS_LDY \
  (MOS65XX_MODEFLAG_IMM \
  | MOS65XX_MODEFLAG_PGE \
  | MOS65XX_MODEFLAG_ABS \
  | MOS65XX_MODEFLAG_IDX \
  | MOS65XX_MODEFLAG_ABS_IDX)

#define MOS65XX_CLASS_IMPLIED MOS65XX_MODEFLAG_IMPLIED

#define MOS65XX_CLASS_JUMP \
  (MOS65XX_MODEFLAG_ABS \
  | MOS65XX_MODEFLAG_LNG \
  | MOS65XX_MODEFLAG_IND \
  | MOS65XX_MODEFLAG_IND_IDX \
  | MOS65XX_MODEFLAG_IND_LNG)

#define MOS65XX_CLASS_BRANCH    (MOS65XX_MODEFLAG_ABS | MOS65XX_MODEFLAG_PCREL)
#define MOS65XX_CLASS_BLOCK     MOS65XX_MODEFLAG_BLK
#define MOS65XX_CLASS_CMP_IDXY  \
  (MOS65XX_MODEFLAG_IMM \
  | MOS65XX_MODEFLAG_PGE \
  | MOS65XX_MODEFLAG_ABS)

#define MOS65XX_ADC_CLASS 			MOS65XX_CLASS_ALUMEM
#define MOS65XX_AND_CLASS 			MOS65XX_CLASS_ALUMEM
#define MOS65XX_ASL_CLASS 			MOS65XX_CLASS_BITOPS
#define MOS65XX_BCC_CLASS 			MOS65XX_CLASS_BRANCH
#define MOS65XX_BCS_CLASS 			MOS65XX_CLASS_BRANCH
#define MOS65XX_BEQ_CLASS 			MOS65XX_CLASS_BRANCH
#define MOS65XX_BIT_CLASS 			MOS65XX_CLASS_LDY
#define MOS65XX_BMI_CLASS 			MOS65XX_CLASS_BRANCH
#define MOS65XX_BNE_CLASS 			MOS65XX_CLASS_BRANCH
#define MOS65XX_BPL_CLASS 			MOS65XX_CLASS_BRANCH
#define MOS65XX_BRA_CLASS 			MOS65XX_CLASS_BRANCH
#define MOS65XX_BRK_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_BRL_CLASS 			MOS65XX_CLASS_BRANCH
#define MOS65XX_BVC_CLASS 			MOS65XX_CLASS_BRANCH
#define MOS65XX_BVS_CLASS 			MOS65XX_CLASS_BRANCH
#define MOS65XX_CLC_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_CLD_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_CLI_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_CLV_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_CMP_CLASS 			MOS65XX_CLASS_ALUMEM
#define MOS65XX_COP_CLASS 			MOS65XX_MODEFLAG_IMM
#define MOS65XX_CPX_CLASS 			MOS65XX_CLASS_CMP_IDXY
#define MOS65XX_CPY_CLASS 			MOS65XX_CLASS_CMP_IDXY
#define MOS65XX_DEC_CLASS 			MOS65XX_CLASS_BITOPS
#define MOS65XX_DEX_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_DEY_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_EOR_CLASS 			MOS65XX_CLASS_ALUMEM
#define MOS65XX_INC_CLASS 			MOS65XX_CLASS_BITOPS
#define MOS65XX_INX_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_INY_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_JMP_CLASS 			MOS65XX_CLASS_JUMP
#define MOS65XX_JSR_CLASS 			MOS65XX_CLASS_JUMP
#define MOS65XX_LDA_CLASS 			MOS65XX_CLASS_ALUMEM
#define MOS65XX_LDX_CLASS 			MOS65XX_CLASS_LDX
#define MOS65XX_LDY_CLASS 			MOS65XX_CLASS_LDY
#define MOS65XX_LSR_CLASS 			MOS65XX_CLASS_BITOPS
#define MOS65XX_MVN_CLASS 			MOS65XX_CLASS_BLOCK
#define MOS65XX_MVP_CLASS 			MOS65XX_CLASS_BLOCK
#define MOS65XX_NOP_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_ORA_CLASS 			MOS65XX_CLASS_ALUMEM
#define MOS65XX_PEA_CLASS 			MOS65XX_MODEFLAG_ABS
#define MOS65XX_PEI_CLASS 			MOS65XX_MODEFLAG_IND
#define MOS65XX_PER_CLASS 			MOS65XX_MODEFLAG_ABS
#define MOS65XX_PHA_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_PHB_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_PHD_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_PHD_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_PHK_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_PHP_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_PHX_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_PHY_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_PLA_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_PLB_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_PLD_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_PLP_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_PLX_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_PLY_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_REP_CLASS 			MOS65XX_MODEFLAG_IMM
#define MOS65XX_ROL_CLASS 			MOS65XX_CLASS_BITOPS
#define MOS65XX_ROR_CLASS 			MOS65XX_CLASS_BITOPS
#define MOS65XX_RTI_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_RTL_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_RTS_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_SBC_CLASS 			MOS65XX_CLASS_ALUMEM
#define MOS65XX_SEC_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_SED_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_SEI_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_SEP_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_STA_CLASS 			MOS65XX_CLASS_ALUMEM
#define MOS65XX_STP_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_STX_CLASS 			(MOS65XX_MODEFLAG_PGE | MOS65XX_MODEFLAG_ABS | MOS65XX_MODEFLAG_IDY)
#define MOS65XX_STY_CLASS 			(MOS65XX_MODEFLAG_PGE | MOS65XX_MODEFLAG_ABS | MOS65XX_MODEFLAG_IDX)
#define MOS65XX_STZ_CLASS 			(MOS65XX_MODEFLAG_PGE | MOS65XX_MODEFLAG_ABS | MOS65XX_MODEFLAG_IDX | MOS65XX_MODEFLAG_ABS_IDX)
#define MOS65XX_TAX_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_TAY_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_TCD_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_TCS_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_TDC_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_TRB_CLASS 			(MOS65XX_MODEFLAG_PGE | MOS65XX_MODEFLAG_ABS)
#define MOS65XX_TSB_CLASS 			(MOS65XX_MODEFLAG_PGE | MOS65XX_MODEFLAG_ABS)
#define MOS65XX_TSC_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_TSX_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_TXA_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_TXS_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_TXY_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_TYA_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_TYX_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_WAI_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_WDM_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_XBA_CLASS 			MOS65XX_CLASS_IMPLIED
#define MOS65XX_XCE_CLASS 			MOS65XX_CLASS_IMPLIED

#define MOS65XX_OPCREATE(name)                  ((MOS65XX_ ## name ## _BASE) | (MOS65XX_ ## name ## _CLASS << 8))

static const struct mos65xx_op mos65xx_opcodes[] = 
{
  { "adc", MOS65XX_OPCREATE(ADC) },
  { "and", MOS65XX_OPCREATE(AND) },
  { "asl", MOS65XX_OPCREATE(ASL) },
  { "bcc", MOS65XX_OPCREATE(BCC) },
  { "bcs", MOS65XX_OPCREATE(BCS) },
  { "beq", MOS65XX_OPCREATE(BEQ) },
  { "bit", MOS65XX_OPCREATE(BIT) },
  { "bmi", MOS65XX_OPCREATE(BMI) },
  { "bne", MOS65XX_OPCREATE(BNE) },
  { "bpl", MOS65XX_OPCREATE(BPL) },
  { "bra", MOS65XX_OPCREATE(BRA) },
  { "brk", MOS65XX_OPCREATE(BRK) },
  { "brl", MOS65XX_OPCREATE(BRL) },
  { "bvc", MOS65XX_OPCREATE(BVC) },
  { "bvs", MOS65XX_OPCREATE(BVS) },
  { "clc", MOS65XX_OPCREATE(CLC) },
  { "cld", MOS65XX_OPCREATE(CLD) },
  { "cli", MOS65XX_OPCREATE(CLI) },
  { "clv", MOS65XX_OPCREATE(CLV) },
  { "cmp", MOS65XX_OPCREATE(CMP) },
  { "cop", MOS65XX_OPCREATE(COP) },
  { "cpx", MOS65XX_OPCREATE(CPX) },
  { "cpy", MOS65XX_OPCREATE(CPY) },
  { "dec", MOS65XX_OPCREATE(DEC) },
  { "dex", MOS65XX_OPCREATE(DEX) },
  { "dey", MOS65XX_OPCREATE(DEY) },
  { "eor", MOS65XX_OPCREATE(EOR) },
  { "inc", MOS65XX_OPCREATE(INC) },
  { "inx", MOS65XX_OPCREATE(INX) },
  { "iny", MOS65XX_OPCREATE(INY) },
  { "jmp", MOS65XX_OPCREATE(JMP) },
  { "jsr", MOS65XX_OPCREATE(JSR) },
  { "lda", MOS65XX_OPCREATE(LDA) },
  { "ldx", MOS65XX_OPCREATE(LDX) },
  { "ldy", MOS65XX_OPCREATE(LDY) },
  { "lsr", MOS65XX_OPCREATE(LSR) },
  { "mvn", MOS65XX_OPCREATE(MVN) },
  { "mvp", MOS65XX_OPCREATE(MVP) },
  { "nop", MOS65XX_OPCREATE(NOP) },
  { "ora", MOS65XX_OPCREATE(ORA) },
  { "pea", MOS65XX_OPCREATE(PEA) },
  { "pei", MOS65XX_OPCREATE(PEI) },
  { "per", MOS65XX_OPCREATE(PER) },
  { "pha", MOS65XX_OPCREATE(PHA) },
  { "phb", MOS65XX_OPCREATE(PHB) },
  { "phd", MOS65XX_OPCREATE(PHD) },
  { "phk", MOS65XX_OPCREATE(PHK) },
  { "php", MOS65XX_OPCREATE(PHP) },
  { "phx", MOS65XX_OPCREATE(PHX) },
  { "phy", MOS65XX_OPCREATE(PHY) },
  { "pla", MOS65XX_OPCREATE(PLA) },
  { "plb", MOS65XX_OPCREATE(PLB) },
  { "pld", MOS65XX_OPCREATE(PLD) },
  { "plp", MOS65XX_OPCREATE(PLP) },
  { "plx", MOS65XX_OPCREATE(PLX) },
  { "ply", MOS65XX_OPCREATE(PLY) },
  { "rep", MOS65XX_OPCREATE(REP) },
  { "rol", MOS65XX_OPCREATE(ROL) },
  { "ror", MOS65XX_OPCREATE(ROR) },
  { "rti", MOS65XX_OPCREATE(RTI) },
  { "rtl", MOS65XX_OPCREATE(RTL) },
  { "rts", MOS65XX_OPCREATE(RTS) },
  { "sbc", MOS65XX_OPCREATE(SBC) },
  { "sec", MOS65XX_OPCREATE(SEC) },
  { "sed", MOS65XX_OPCREATE(SED) },
  { "sei", MOS65XX_OPCREATE(SEI) },
  { "sep", MOS65XX_OPCREATE(SEP) },
  { "sta", MOS65XX_OPCREATE(STA) },
  { "stp", MOS65XX_OPCREATE(STP) },
  { "stx", MOS65XX_OPCREATE(STX) },
  { "sty", MOS65XX_OPCREATE(STY) },
  { "stz", MOS65XX_OPCREATE(STZ) },
  { "tax", MOS65XX_OPCREATE(TAX) },
  { "tay", MOS65XX_OPCREATE(TAY) },
  { "tcd", MOS65XX_OPCREATE(TCD) },
  { "tcs", MOS65XX_OPCREATE(TCS) },
  { "tdc", MOS65XX_OPCREATE(TDC) },
  { "trb", MOS65XX_OPCREATE(TRB) },
  { "tsb", MOS65XX_OPCREATE(TSB) },
  { "tsc", MOS65XX_OPCREATE(TSC) },
  { "tsx", MOS65XX_OPCREATE(TSX) },
  { "txa", MOS65XX_OPCREATE(TXA) },
  { "txs", MOS65XX_OPCREATE(TSX) },
  { "txy", MOS65XX_OPCREATE(TXY) },
  { "tya", MOS65XX_OPCREATE(TYA) },
  { "tyx", MOS65XX_OPCREATE(TYX) },
  { "wai", MOS65XX_OPCREATE(WAI) },
  { "wdm", MOS65XX_OPCREATE(WDM)},
  { "xba", MOS65XX_OPCREATE(XBA) },
  { "xce", MOS65XX_OPCREATE(XCE) } 
};
#define MOS65XX_OPCODES_SIZE (sizeof(mos65xx_opcodes) / sizeof(mos65xx_opcodes[0]))

static int mos65xx_op_compare(const struct mos65xx_op *left, const struct mos65xx_op *right)
{
  return strcasecmp(left->name, right->name); 
}

struct mos65xx_op *mos65xx_opcode_lookup(const char *nmemonic)
{
  struct mos65xx_op dummy = {nmemonic, 0};
  return bsearch(&dummy, mos65xx_opcodes, 
    sizeof(mos65xx_opcodes) / sizeof(mos65xx_opcodes[0]),
    sizeof(mos65xx_opcodes[0]),
    (int(*)(const void *, const void *))mos65xx_op_compare);  
}

