
#include <opcode/mos65xx.h>
#include <strings.h>
#include <stdlib.h>
#include <stdio.h>

static const struct mos65xx_op mos65xx_opcodes[] = 
{
  { "adc", MOS65XX_OPCODE_ALUMEM | MOS65XX_ADC_BASE },
  { "and", MOS65XX_OPCODE_ALUMEM | MOS65XX_AND_BASE },
  { "asl", MOS65XX_OPCODE_BITOPS | MOS65XX_ASL_BASE },
  { "bcc", MOS65XX_OPCODE_BRANCH | MOS65XX_BCC_BASE },
  { "bcs", MOS65XX_OPCODE_BRANCH | MOS65XX_BCS_BASE },
  { "beq", MOS65XX_OPCODE_BRANCH | MOS65XX_BEQ_BASE },
  { "bit", MOS65XX_OPCODE_LDY | MOS65XX_BIT_BASE },
  { "bmi", MOS65XX_OPCODE_BRANCH | MOS65XX_BMI_BASE },
  { "bne", MOS65XX_OPCODE_BRANCH | MOS65XX_BNE_BASE },
  { "bpl", MOS65XX_OPCODE_BRANCH | MOS65XX_BPL_BASE },
  { "bra", MOS65XX_OPCODE_BRANCH | MOS65XX_BRA_BASE },
  { "brk", MOS65XX_OPCODE_NOARGS | MOS65XX_BRK_BASE },
  { "brl", MOS65XX_OPCODE_BRANCH | MOS65XX_BRL_BASE },
  { "bvc", MOS65XX_OPCODE_BRANCH | MOS65XX_BVC_BASE },
  { "bvs", MOS65XX_OPCODE_BRANCH | MOS65XX_BVS_BASE },
  { "clc", MOS65XX_OPCODE_NOARGS | MOS65XX_CLC_BASE },
  { "cld", MOS65XX_OPCODE_NOARGS | MOS65XX_CLD_BASE },
  { "cli", MOS65XX_OPCODE_NOARGS | MOS65XX_CLI_BASE },
  { "clv", MOS65XX_OPCODE_NOARGS | MOS65XX_CLV_BASE },
  { "cmp", MOS65XX_OPCODE_ALUMEM | MOS65XX_CMP_BASE },
  { "cop", MOS65XX_OPCODE_SPECIAL_COP | MOS65XX_COP_BASE },
  { "cpx", MOS65XX_OPCODE_LDX | MOS65XX_CPX_BASE },
  { "cpy", MOS65XX_OPCODE_LDY | MOS65XX_CPY_BASE },
  { "dec", MOS65XX_OPCODE_BITOPS | MOS65XX_DEC_BASE },
  { "dex", MOS65XX_OPCODE_NOARGS | MOS65XX_DEX_BASE },
  { "dey", MOS65XX_OPCODE_NOARGS | MOS65XX_DEY_BASE },
  { "eor", MOS65XX_OPCODE_ALUMEM | MOS65XX_EOR_BASE },
  { "inc", MOS65XX_OPCODE_BITOPS | MOS65XX_INC_BASE },
  { "inx", MOS65XX_OPCODE_NOARGS | MOS65XX_INX_BASE },
  { "iny", MOS65XX_OPCODE_NOARGS | MOS65XX_INY_BASE },
  { "jmp", MOS65XX_OPCODE_JUMP | MOS65XX_JMP_BASE },
  { "jsr", MOS65XX_OPCODE_JUMP | MOS65XX_JSR_BASE },
  { "lda", MOS65XX_OPCODE_ALUMEM | MOS65XX_LDA_BASE },
  { "ldx", MOS65XX_OPCODE_LDX | MOS65XX_LDX_BASE },
  { "ldy", MOS65XX_OPCODE_LDY | MOS65XX_LDY_BASE },
  { "lsr", MOS65XX_OPCODE_BITOPS | MOS65XX_LSR_BASE },
  { "mvn", MOS65XX_OPCODE_SPECIAL_MVNP | MOS65XX_MVN_BASE },
  { "mvp", MOS65XX_OPCODE_SPECIAL_MVNP | MOS65XX_MVP_BASE },
  { "nop", MOS65XX_OPCODE_NOARGS | MOS65XX_NOP_BASE },
  { "ora", MOS65XX_OPCODE_ALUMEM | MOS65XX_ORA_BASE },
  { "pea", MOS65XX_OPCODE_SPECIAL_PEA | MOS65XX_PEA_BASE },
  { "pei", MOS65XX_OPCODE_SPECIAL_PEI | MOS65XX_PEI_BASE },
  { "per", MOS65XX_OPCODE_SPECIAL_PER | MOS65XX_PER_BASE },
  { "pha", MOS65XX_OPCODE_NOARGS | MOS65XX_PHA_BASE },
  { "phb", MOS65XX_OPCODE_NOARGS | MOS65XX_PHB_BASE },
  { "phd", MOS65XX_OPCODE_NOARGS | MOS65XX_PHD_BASE },
  { "phk", MOS65XX_OPCODE_NOARGS | MOS65XX_PHK_BASE },
  { "php", MOS65XX_OPCODE_NOARGS | MOS65XX_PHP_BASE },
  { "phx", MOS65XX_OPCODE_NOARGS | MOS65XX_PHX_BASE },
  { "phy", MOS65XX_OPCODE_NOARGS | MOS65XX_PHY_BASE },
  { "pla", MOS65XX_OPCODE_NOARGS | MOS65XX_PLA_BASE },
  { "plb", MOS65XX_OPCODE_NOARGS | MOS65XX_PLB_BASE },
  { "pld", MOS65XX_OPCODE_NOARGS | MOS65XX_PLD_BASE },
  { "plp", MOS65XX_OPCODE_NOARGS | MOS65XX_PLP_BASE },
  { "plx", MOS65XX_OPCODE_NOARGS | MOS65XX_PLX_BASE },
  { "ply", MOS65XX_OPCODE_NOARGS | MOS65XX_PLY_BASE },
  { "rep", MOS65XX_OPCODE_SPECIAL_REP | MOS65XX_REP_BASE },
  { "rol", MOS65XX_OPCODE_BITOPS | MOS65XX_ROL_BASE },
  { "ror", MOS65XX_OPCODE_BITOPS | MOS65XX_ROR_BASE },
  { "rti", MOS65XX_OPCODE_NOARGS | MOS65XX_RTI_BASE },
  { "rtl", MOS65XX_OPCODE_NOARGS | MOS65XX_RTL_BASE },
  { "rts", MOS65XX_OPCODE_NOARGS | MOS65XX_RTS_BASE },
  { "sbc", MOS65XX_OPCODE_ALUMEM | MOS65XX_SBC_BASE },
  { "sec", MOS65XX_OPCODE_NOARGS | MOS65XX_SEC_BASE },
  { "sed", MOS65XX_OPCODE_NOARGS | MOS65XX_SED_BASE },
  { "sei", MOS65XX_OPCODE_NOARGS | MOS65XX_SEI_BASE },
  { "sep", MOS65XX_OPCODE_NOARGS | MOS65XX_SEP_BASE },
  { "sta", MOS65XX_OPCODE_ALUMEM | MOS65XX_STA_BASE },
  { "stp", MOS65XX_OPCODE_NOARGS | MOS65XX_STP_BASE },
  { "stx", MOS65XX_OPCODE_LDX | MOS65XX_STX_BASE },
  { "sty", MOS65XX_OPCODE_LDY | MOS65XX_STY_BASE },
  { "stz", MOS65XX_OPCODE_LDY | MOS65XX_STZ_BASE },
  { "tax", MOS65XX_OPCODE_NOARGS | MOS65XX_TAX_BASE },
  { "tay", MOS65XX_OPCODE_NOARGS | MOS65XX_TAY_BASE },
  { "tcd", MOS65XX_OPCODE_NOARGS | MOS65XX_TCD_BASE },
  { "tcs", MOS65XX_OPCODE_NOARGS | MOS65XX_TCS_BASE },
  { "tdc", MOS65XX_OPCODE_NOARGS | MOS65XX_TDC_BASE },
  { "trb", MOS65XX_OPCODE_SPECIAL_TRSB | MOS65XX_TRB_BASE },
  { "tsb", MOS65XX_OPCODE_SPECIAL_TRSB | MOS65XX_TSB_BASE },
  { "tsc", MOS65XX_OPCODE_NOARGS | MOS65XX_TSC_BASE },
  { "tsx", MOS65XX_OPCODE_NOARGS | MOS65XX_TSX_BASE },
  { "txa", MOS65XX_OPCODE_NOARGS | MOS65XX_TXA_BASE },
  { "txs", MOS65XX_OPCODE_NOARGS | MOS65XX_TSX_BASE },
  { "txy", MOS65XX_OPCODE_NOARGS | MOS65XX_TXY_BASE },
  { "tya", MOS65XX_OPCODE_NOARGS | MOS65XX_TYA_BASE },
  { "tyx", MOS65XX_OPCODE_NOARGS | MOS65XX_TYX_BASE },
  { "wai", MOS65XX_OPCODE_NOARGS | MOS65XX_WAI_BASE },
  { "wdm", MOS65XX_OPCODE_NOARGS | MOS65XX_WDM_BASE},
  { "xba", MOS65XX_OPCODE_NOARGS | MOS65XX_XBA_BASE },
  { "xce", MOS65XX_OPCODE_NOARGS | MOS65XX_XCE_BASE } 
};
#define MOS65XX_OPCODES_SIZE (sizeof(mos65xx_opcodes) / sizeof(mos65xx_opcodes[0]))

static int mos65xx_op_compare(const struct mos65xx_op *left, const struct mos65xx_op *right)
{
  return strcasecmp(left->name, right->name); 
}

struct mos65xx_op *mos65xx_opcode_lookup(const char *nmemonic)
{
  struct mos65xx_op dummy = {nmemonic, 0};
  return bsearch(&dummy, mos65xx_opcodes, 
    sizeof(mos65xx_opcodes) / sizeof(mos65xx_opcodes[0]),
    sizeof(mos65xx_opcodes[0]),
    (int(*)(const void *, const void *))mos65xx_op_compare);  
}

