#ifndef MOS65XX_OPC
#define MOS65XX_OPC

#include <opcode/mos65xx.h>

struct mos65xx_oplookup
{
  const char *name;
  uint8_t base;
  uint8_t opclass;
};
#define MOS65XX_OPCREATE(name) { #name, MOS65XX_ ## name ## _BASE,  MOS65XX_ ## name ## _CLASS }

/*
 *  Do not take changing these modeflags lightly.
 *  If you change the modeflags, you change what
 *  modes instructions accept, which changes what addends
 *  they receive, possibly decoding the wrong opcode.
 *  Change at your own risk.
 */
#define MOS65XX_ALUMEM_MODEFLAGS \
  (MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IND_IDX) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_STK_REL) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_PGE) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IND_LNG) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IMM) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_LNG) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IND_IDY) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IND) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_STK_IND_IDY) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IDX) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IND_LNG_IDY) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS_IDY) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS_IDX) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS_LNG_IDX))

#define MOS65XX_STA_MODEFLAGS \
  (MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IND_IDX) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_STK_REL) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_PGE) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IND_LNG) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_LNG) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IND_IDY) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IND) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_STK_IND_IDY) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IDX) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IND_LNG_IDY) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS_IDY) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS_IDX) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS_LNG_IDX))

#define MOS65XX_BITOPS_MODEFLAGS \
  (MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_PGE) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ACC) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IDX) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS_IDX))

#define MOS65XX_BRANCH_MODEFLAGS \
  (MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_PCREL) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS))

#define MOS65XX_BRANCHLONG_MODEFLAGS \
  (MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_PCREL16) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS))

#define MOS65XX_IDX_MODEFLAGS \
  (MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IMM) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_PGE) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IDX) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS_IDX))


#define MOS65XX_IDY_MODEFLAGS \
  (MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IMM) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_PGE) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IDY) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS_IDY))

#define MOS65XX_IMPLIED_MODEFLAGS MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IMPLIED)

#define MOS65XX_CPXY_MODEFLAGS \
  (MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IMM) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_PGE) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS))

#define MOS65XX_JUMP_MODEFLAGS \
  (MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_LNG) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS_IND) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS_IDX) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS_IND_LNG))

#define MOS65XX_JSR_MODEFLAGS \
  (MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_LNG) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS_IDX))

#define MOS65XX_BLK_MODEFLAGS 	MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_BLK)
#define MOS65XX_PEA_MODEFLAGS 	MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS)
#define MOS65XX_PEI_MODEFLAGS 	MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IND)

#define MOS65XX_PER_MODEFLAGS \
  (MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_PCREL16) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS))

#define MOS65XX_IMM_MODEFLAGS 	MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IMM)

#define MOS65XX_STX_MODEFLAGS \
  (MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IDY) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_PGE) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS))

#define MOS65XX_STY_MODEFLAGS \
  (MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IDX) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_PGE) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS))

#define MOS65XX_STZ_MODEFLAGS \
  (MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_IDX) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS_IDX) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_PGE) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS))

#define MOS65XX_TB_MODEFLAGS \
  (MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_PGE) \
  | MOS65XX_MODEFLAG(MOS65XX_ADDRMODE_ABS))

#endif
